# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ee2c4c35b9ca1ee57c272f0acc9a8af957a6dbbfd790dd66b4fb7f0777da21837b1036e3511b72298abbc2ccee3154c237a033256e6c48d6970728ca89cb04

test:
  secret_key_base: 41b31427dab127b5ca89d5d4a56a2bf3038de4daabd43cab7a0df2b435948d916bf61629bb2a1e8165ac325ceba264eace4a190b679889784188b53e5936416e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
